/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.controlador.Cancionesbd;
import com.istloja.modelTables.ModelTableCanciones;

/**
 *
 * @author jpsolanoc
 */
public class ListaDeCanciones extends javax.swing.JDialog {

    /**
     * Creates new form ListaDeCanciones
     */
    private ModelTableCanciones modelTableCanciones;
    private Cancionesbd controladorCanciones;
    public ListaDeCanciones(java.awt.Frame parent, boolean modal,ModelTableCanciones modelTableInventario,Cancionesbd controladorCanciones) {
        super(parent, modal);
        this.modelTableCanciones = modelTableInventario;
        this.controladorCanciones = controladorCanciones;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        comboBoxCancionesBusqueda = new javax.swing.JComboBox<>();
        txtCancionesBusqueda = new javax.swing.JTextField();
        btnCancionBusqueda = new javax.swing.JButton();
        tblInventario = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Avanzada Productos");

        jLabel14.setText("Busqueda");

        comboBoxCancionesBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Artista", "Grupo", "Album" }));
        comboBoxCancionesBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCancionesBusquedaActionPerformed(evt);
            }
        });

        btnCancionBusqueda.setText("Buscar");
        btnCancionBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionBusquedaActionPerformed(evt);
            }
        });

        jTable1.setModel(modelTableCanciones);
        tblInventario.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1172, Short.MAX_VALUE)
                .addComponent(btnCancionBusqueda)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(comboBoxCancionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCancionesBusqueda))
                        .addComponent(tblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnCancionBusqueda)
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(comboBoxCancionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCancionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addComponent(tblInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancionBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionBusquedaActionPerformed
        // TODO add your handling code here:
        System.out.println("Combo" + comboBoxCancionesBusqueda.getSelectedIndex());
            switch (comboBoxCancionesBusqueda.getSelectedIndex()) {
            case 0:
                modelTableCanciones.setCanciones(controladorCanciones.getCancionTituloListo(txtCancionesBusqueda.getText()));
                modelTableCanciones.fireTableDataChanged();
                break;
            case 1:
                modelTableCanciones.setCanciones(controladorCanciones.getCancionArtistaListo(txtCancionesBusqueda.getText()));
                modelTableCanciones.fireTableDataChanged();
                break;
            case 2:
                modelTableCanciones.setCanciones(controladorCanciones.getCancionGrupoListo(txtCancionesBusqueda.getText()));
                modelTableCanciones.fireTableDataChanged();
                break;
            case 3:
                modelTableCanciones.setCanciones(controladorCanciones.getCancionAlbumListo(txtCancionesBusqueda.getText()));
                modelTableCanciones.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnCancionBusquedaActionPerformed

    private void comboBoxCancionesBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCancionesBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCancionesBusquedaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancionBusqueda;
    private javax.swing.JComboBox<String> comboBoxCancionesBusqueda;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblInventario;
    private javax.swing.JTextField txtCancionesBusqueda;
    // End of variables declaration//GEN-END:variables
}
